version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: blueflag/client-build:0.0.7

    steps:
      - checkout

      - restore_cache:
          keys: ['unmutable-deps-{{ checksum "yarn.lock" }}']
      - restore_cache:
          keys: ['deep-memo-deps-{{ checksum "yarn.lock" }}']
      - restore_cache:
          keys: ['unmutable-docs-deps-{{ checksum "yarn.lock" }}']

      - run: yarn install
      - run: yarn bootstrap
      - run: yarn build

      - save_cache:
          key: unmutable-deps-{{ checksum "yarn.lock" }}
          paths: ['packages/unmutable/node_modules']

      - save_cache:
          key: deep-memo-deps-{{ checksum "yarn.lock" }}
          paths: ['packages/deep-memo/node_modules']

      - save_cache:
          key: unmutable-docs-deps-{{ checksum "yarn.lock" }}
          paths: ['packages/unmutable-docs/node_modules']

      - run: git diff | cat
      - run: test -z "$(git status --porcelain)"
      - run: yarn test-all

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
